version: 2.1

orbs:
  clair-scanner: ovotech/clair-scanner@1.6.0

jobs:
  build-image:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build-image
          command: |
            make build-image

  scan-images:
    executor: clair_scanner/default
    steps:
    - clair_scanner/scan:
        image: debian:stretch            

  build-publish:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build-publish
          command: |
            make build-publish

workflows:
  workflow:
    jobs:
      - build-image:
          context: CI
      - scan-images
      - build-publish:
          context: CI
