version: 2.1

orbs:
  clair_scanner: ovotech/clair-scanner@1

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build
          command: |
            make build

  scan:
    executor: clair_scanner/default
    steps:
    - clair_scanner/scan:
        image: debian:stretch            

  publish:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: publish
          command: |
            make publish

workflows:
  workflow:
    jobs:
      - build:
          context: CI
      - scan
      - publish:
          context: CI
