# https://circleci.com/docs/2.0/config-intro
version: 2.1

jobs:
  build:
    docker:
      - image: afonsoaugusto/base-ci:latest
    #machine: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            make build

workflows:
  workflow:
    jobs:
      - build:
          context: CI
